<cfoutput>
<div 
    id="customPokedexTable" 
    class="mt-xl-3" 
    data-trainerid="#encodeForHTMLAttribute(prc.trainerid)#" 
    data-customid="#encodeForHTMLAttribute(prc.customid)#" 
    data-shiny="#encodeForHTMLAttribute(rc.shiny)#"
>
</div>
</cfoutput>